name: Remote update execution
on:
  push:
    branches:
      - main
env:
  # Use docker.io for Docker Hub if empty
  PROJECT_NAME: minesweeper
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          mkdir -p /app/${{ env.PROJECT_NAME }}
          cd /app/${{ env.PROJECT_NAME }}
          if [ -f docker-compose.yml ]; then docker-compose stop; fi
          curl https://raw.githubusercontent.com/allyusd/minesweeper/main/docker-compose.yml -o docker-compose.yml
          cat docker-compose.yml
          docker-compose pull
          docker-compose up -d
